timeout: 0

/arc_os
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    module_path: boot():/boot/init
    module_path: boot():/boot/login
    module_path: boot():/boot/hello
    module_path: boot():/boot/echo
    module_path: boot():/boot/shell
    module_path: boot():/boot/cat
    module_path: boot():/boot/wc
    module_path: boot():/boot/head
    module_path: boot():/boot/tail
    module_path: boot():/boot/touch
    module_path: boot():/boot/mkdir
    module_path: boot():/boot/rm
    module_path: boot():/boot/ls
    module_path: boot():/boot/stat
    module_path: boot():/boot/chmod
    module_path: boot():/boot/chown
    module_path: boot():/boot/cp
    module_path: boot():/boot/mv
    module_path: boot():/boot/ps
    module_path: boot():/boot/kill
    module_path: boot():/boot/uname
    module_path: boot():/boot/grep
    module_path: boot():/boot/free
