/* arc_os — Host-side tests for FAT32 filesystem */

#include "test_framework.h"
#include <stdint.h>

/* Guard kernel headers that we stub */
#define ARCHOS_LIB_KPRINTF_H
#define ARCHOS_MM_KMALLOC_H
#define ARCHOS_LIB_MEM_H
#define ARCHOS_LIB_STRING_H
#define ARCHOS_DRIVERS_VIRTIO_BLK_H

/* Stub kprintf */
static inline void kprintf(const char *fmt, ...) { (void)fmt; }

/* Allocation flags */
#define GFP_KERNEL  0x00
#define GFP_ZERO    0x01

/* kmalloc/kfree stubs using libc */
static void *kmalloc(size_t size, uint32_t flags) {
    void *p = malloc(size);
    if (p && (flags & GFP_ZERO)) memset(p, 0, size);
    return p;
}
static void kfree(void *ptr) { free(ptr); }
static void *krealloc(void *ptr, size_t new_size) { return realloc(ptr, new_size); }

/* VirtIO-blk stub: reads/writes from a file on disk */
static FILE *disk_file;

static int virtio_blk_read(uint64_t sector, uint32_t count, void *buf) {
    if (!disk_file) return -1;
    if (fseek(disk_file, (long)(sector * 512), SEEK_SET) != 0) return -1;
    return (fread(buf, 512, count, disk_file) == count) ? 0 : -1;
}

static int virtio_blk_write(uint64_t sector, uint32_t count, const void *buf) {
    if (!disk_file) return -1;
    if (fseek(disk_file, (long)(sector * 512), SEEK_SET) != 0) return -1;
    if (fwrite(buf, 512, count, disk_file) != count) return -1;
    fflush(disk_file);
    return 0;
}

/* Include FAT32 implementation only (vfs.c already compiled in test_vfs.c) */
#include "../kernel/fs/fat32.c"

/* Path to the test disk image — generated by tools/make-fat32-test-disk.sh */
static const char *test_disk_path = "tests/fat32_test.img";

/* Helper: open disk, mount FAT32, return root node */
static VfsNode *mount_test_disk(void) {
    disk_file = fopen(test_disk_path, "r+b");
    if (!disk_file) {
        /* Try from build directory */
        disk_file = fopen("../tests/fat32_test.img", "r+b");
    }
    if (!disk_file) return NULL;

    /* Reset FAT32-internal state */
    node_cache_count = 0;
    next_fat_inode = 0x10000;

    return fat32_mount();
}

static void unmount_test_disk(void) {
    if (disk_file) {
        fclose(disk_file);
        disk_file = NULL;
    }
}

/* Helper to create a fresh writable copy of the test disk for write tests */
static VfsNode *mount_writable_copy(void) {
    /* Copy original to temp file */
    FILE *src = fopen(test_disk_path, "rb");
    if (!src) src = fopen("../tests/fat32_test.img", "rb");
    if (!src) return NULL;

    FILE *dst = tmpfile();
    if (!dst) { fclose(src); return NULL; }

    char buf[4096];
    size_t n;
    while ((n = fread(buf, 1, sizeof(buf), src)) > 0) {
        fwrite(buf, 1, n, dst);
    }
    fclose(src);
    fflush(dst);
    rewind(dst);

    disk_file = dst;
    node_cache_count = 0;
    next_fat_inode = 0x10000;

    return fat32_mount();
}

/* === Read-path tests === */

static int test_bpb_parse_valid(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    ASSERT_EQ(root->type, VFS_DIRECTORY);
    unmount_test_disk();
    return 0;
}

static int test_bpb_reject_bad_sector_size(void) {
    /* Create a tiny invalid image */
    disk_file = tmpfile();
    ASSERT_TRUE(disk_file != NULL);
    /* Write 512 bytes of zeros — bytes_per_sector will be 0 */
    char zeros[512];
    memset(zeros, 0, sizeof(zeros));
    fwrite(zeros, 1, sizeof(zeros), disk_file);
    fflush(disk_file);
    rewind(disk_file);

    node_cache_count = 0;
    VfsNode *root = fat32_mount();
    ASSERT_TRUE(root == NULL);
    fclose(disk_file);
    disk_file = NULL;
    return 0;
}

static int test_fat_table_loaded(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    Fat32NodeInfo *info = to_fat32(root);
    /* FAT entries for cluster 2 (root) should be non-free */
    uint32_t root_entry = info->vol->fat[info->vol->root_cluster] & FAT32_ENTRY_MASK;
    ASSERT_TRUE(root_entry != FAT32_FREE);
    unmount_test_disk();
    return 0;
}

static int test_root_readdir(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);

    VfsDirEntry entries[16];
    int count = root->ops->readdir(root, entries, 16);
    ASSERT_TRUE(count >= 2);  /* hello.txt and subdir at minimum */

    /* Find hello.txt and subdir */
    int found_hello = 0, found_subdir = 0;
    for (int i = 0; i < count; i++) {
        if (strcmp(entries[i].name, "hello.txt") == 0) {
            found_hello = 1;
            ASSERT_EQ(entries[i].type, VFS_FILE);
        }
        if (strcmp(entries[i].name, "subdir") == 0) {
            found_subdir = 1;
            ASSERT_EQ(entries[i].type, VFS_DIRECTORY);
        }
    }
    ASSERT_TRUE(found_hello);
    ASSERT_TRUE(found_subdir);
    unmount_test_disk();
    return 0;
}

static int test_lookup_file(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    VfsNode *node = root->ops->lookup(root, "hello.txt");
    ASSERT_TRUE(node != NULL);
    ASSERT_EQ(node->type, VFS_FILE);
    unmount_test_disk();
    return 0;
}

static int test_lookup_dir(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    VfsNode *node = root->ops->lookup(root, "subdir");
    ASSERT_TRUE(node != NULL);
    ASSERT_EQ(node->type, VFS_DIRECTORY);
    unmount_test_disk();
    return 0;
}

static int test_lookup_nonexistent(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    VfsNode *node = root->ops->lookup(root, "nope.txt");
    ASSERT_TRUE(node == NULL);
    unmount_test_disk();
    return 0;
}

static int test_lookup_case_insensitive(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    VfsNode *n1 = root->ops->lookup(root, "hello.txt");
    VfsNode *n2 = root->ops->lookup(root, "HELLO.TXT");
    VfsNode *n3 = root->ops->lookup(root, "Hello.Txt");
    ASSERT_TRUE(n1 != NULL);
    ASSERT_TRUE(n2 != NULL);
    ASSERT_TRUE(n3 != NULL);
    unmount_test_disk();
    return 0;
}

static int test_read_file_full(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    VfsNode *node = root->ops->lookup(root, "hello.txt");
    ASSERT_TRUE(node != NULL);
    ASSERT_EQ(node->size, 13);

    char buf[32];
    memset(buf, 0, sizeof(buf));
    int n = node->ops->read(node, buf, 0, sizeof(buf));
    ASSERT_EQ(n, 13);
    ASSERT_MEM_EQ(buf, "Hello, FAT32!", 13);
    unmount_test_disk();
    return 0;
}

static int test_read_file_offset(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    VfsNode *node = root->ops->lookup(root, "hello.txt");
    ASSERT_TRUE(node != NULL);

    char buf[32];
    memset(buf, 0, sizeof(buf));
    int n = node->ops->read(node, buf, 7, sizeof(buf));
    ASSERT_EQ(n, 6);
    ASSERT_MEM_EQ(buf, "FAT32!", 6);
    unmount_test_disk();
    return 0;
}

static int test_read_file_partial(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    VfsNode *node = root->ops->lookup(root, "hello.txt");
    ASSERT_TRUE(node != NULL);

    char buf[5];
    int n = node->ops->read(node, buf, 0, 5);
    ASSERT_EQ(n, 5);
    ASSERT_MEM_EQ(buf, "Hello", 5);
    unmount_test_disk();
    return 0;
}

static int test_read_past_eof(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    VfsNode *node = root->ops->lookup(root, "hello.txt");
    ASSERT_TRUE(node != NULL);

    char buf[16];
    int n = node->ops->read(node, buf, 100, sizeof(buf));
    ASSERT_EQ(n, 0);
    unmount_test_disk();
    return 0;
}

static int test_nested_lookup(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    VfsNode *subdir = root->ops->lookup(root, "subdir");
    ASSERT_TRUE(subdir != NULL);
    ASSERT_EQ(subdir->type, VFS_DIRECTORY);
    VfsNode *nested = subdir->ops->lookup(subdir, "nested.txt");
    ASSERT_TRUE(nested != NULL);
    ASSERT_EQ(nested->type, VFS_FILE);
    unmount_test_disk();
    return 0;
}

static int test_nested_read(void) {
    VfsNode *root = mount_test_disk();
    ASSERT_TRUE(root != NULL);
    VfsNode *subdir = root->ops->lookup(root, "subdir");
    ASSERT_TRUE(subdir != NULL);
    VfsNode *nested = subdir->ops->lookup(subdir, "nested.txt");
    ASSERT_TRUE(nested != NULL);

    char buf[32];
    memset(buf, 0, sizeof(buf));
    int n = nested->ops->read(nested, buf, 0, sizeof(buf));
    ASSERT_EQ(n, 10);
    ASSERT_MEM_EQ(buf, "1234567890", 10);
    unmount_test_disk();
    return 0;
}

static int test_name_8_3_conversion(void) {
    /* Test fat32_name_to_str */
    Fat32DirEntry e;
    char out[13];

    memcpy(e.name, "HELLO   TXT", 11);
    fat32_name_to_str(&e, out);
    ASSERT_STR_EQ(out, "hello.txt");

    memcpy(e.name, "MYDIR      ", 11);
    fat32_name_to_str(&e, out);
    ASSERT_STR_EQ(out, "mydir");

    memcpy(e.name, "README  MD ", 11);
    fat32_name_to_str(&e, out);
    ASSERT_STR_EQ(out, "readme.md");

    /* Test fat32_str_to_name */
    uint8_t fname[11];
    ASSERT_EQ(fat32_str_to_name("hello.txt", fname), 0);
    ASSERT_MEM_EQ(fname, "HELLO   TXT", 11);

    ASSERT_EQ(fat32_str_to_name("mydir", fname), 0);
    ASSERT_MEM_EQ(fname, "MYDIR      ", 11);

    /* Name too long should fail */
    ASSERT_EQ(fat32_str_to_name("toolongname.txt", fname), -1);
    ASSERT_EQ(fat32_str_to_name("file.toolong", fname), -1);

    return 0;
}

/* === Write-path tests === */

static int test_create_file(void) {
    VfsNode *root = mount_writable_copy();
    ASSERT_TRUE(root != NULL);

    VfsNode *node = root->ops->create(root, "new.txt", VFS_FILE);
    ASSERT_TRUE(node != NULL);
    ASSERT_EQ(node->type, VFS_FILE);

    /* Verify it appears in readdir */
    VfsDirEntry entries[16];
    int count = root->ops->readdir(root, entries, 16);
    int found = 0;
    for (int i = 0; i < count; i++) {
        if (strcmp(entries[i].name, "new.txt") == 0) found = 1;
    }
    ASSERT_TRUE(found);
    unmount_test_disk();
    return 0;
}

static int test_write_then_read_fat32(void) {
    VfsNode *root = mount_writable_copy();
    ASSERT_TRUE(root != NULL);

    VfsNode *node = root->ops->create(root, "test.txt", VFS_FILE);
    ASSERT_TRUE(node != NULL);

    const char *data = "FAT32 write test!";
    int written = node->ops->write(node, data, 0, 17);
    ASSERT_EQ(written, 17);

    char buf[32];
    memset(buf, 0, sizeof(buf));
    int n = node->ops->read(node, buf, 0, sizeof(buf));
    ASSERT_EQ(n, 17);
    ASSERT_MEM_EQ(buf, "FAT32 write test!", 17);
    unmount_test_disk();
    return 0;
}

static int test_create_directory(void) {
    VfsNode *root = mount_writable_copy();
    ASSERT_TRUE(root != NULL);

    VfsNode *dir = root->ops->create(root, "newdir", VFS_DIRECTORY);
    ASSERT_TRUE(dir != NULL);
    ASSERT_EQ(dir->type, VFS_DIRECTORY);

    VfsDirEntry entries[16];
    int count = root->ops->readdir(root, entries, 16);
    int found = 0;
    for (int i = 0; i < count; i++) {
        if (strcmp(entries[i].name, "newdir") == 0) {
            found = 1;
            ASSERT_EQ(entries[i].type, VFS_DIRECTORY);
        }
    }
    ASSERT_TRUE(found);
    unmount_test_disk();
    return 0;
}

static int test_unlink_fat32_file(void) {
    VfsNode *root = mount_writable_copy();
    ASSERT_TRUE(root != NULL);

    /* hello.txt exists from the test image */
    VfsNode *node = root->ops->lookup(root, "hello.txt");
    ASSERT_TRUE(node != NULL);

    int ret = root->ops->unlink(root, "hello.txt");
    ASSERT_EQ(ret, 0);

    /* Should no longer appear in lookup */
    node = root->ops->lookup(root, "hello.txt");
    ASSERT_TRUE(node == NULL);
    unmount_test_disk();
    return 0;
}

static int test_truncate_to_zero(void) {
    VfsNode *root = mount_writable_copy();
    ASSERT_TRUE(root != NULL);

    VfsNode *node = root->ops->lookup(root, "hello.txt");
    ASSERT_TRUE(node != NULL);
    ASSERT_TRUE(node->size > 0);

    node->ops->truncate(node, 0);
    ASSERT_EQ(node->size, 0);

    char buf[16];
    int n = node->ops->read(node, buf, 0, sizeof(buf));
    ASSERT_EQ(n, 0);
    unmount_test_disk();
    return 0;
}

/* --- Test suite export --- */

TestCase fat32_tests[] = {
    { "bpb_parse_valid",         test_bpb_parse_valid },
    { "bpb_reject_bad_sector_size", test_bpb_reject_bad_sector_size },
    { "fat_table_loaded",        test_fat_table_loaded },
    { "root_readdir",            test_root_readdir },
    { "lookup_file",             test_lookup_file },
    { "lookup_dir",              test_lookup_dir },
    { "lookup_nonexistent",      test_lookup_nonexistent },
    { "lookup_case_insensitive", test_lookup_case_insensitive },
    { "read_file_full",          test_read_file_full },
    { "read_file_offset",        test_read_file_offset },
    { "read_file_partial",       test_read_file_partial },
    { "read_past_eof",           test_read_past_eof },
    { "nested_lookup",           test_nested_lookup },
    { "nested_read",             test_nested_read },
    { "name_8_3_conversion",     test_name_8_3_conversion },
    { "create_file",             test_create_file },
    { "write_then_read",         test_write_then_read_fat32 },
    { "create_directory",        test_create_directory },
    { "unlink_file",             test_unlink_fat32_file },
    { "truncate_to_zero",        test_truncate_to_zero },
};

int fat32_test_count = sizeof(fat32_tests) / sizeof(fat32_tests[0]);
