/* arc_os — TTY subsystem implementation
 * Line-buffered input with ring buffer for completed lines. */

#include "drivers/tty.h"
#include "arch/x86_64/serial.h"
#include "proc/waitqueue.h"
#include "proc/process.h"
#include "proc/signal.h"
#include "lib/kprintf.h"

/* Ring buffer for completed lines (power-of-2 size) */
#define TTY_BUF_SIZE 256
#define TTY_BUF_MASK (TTY_BUF_SIZE - 1)

/* Max length of a single line being typed */
#define TTY_LINE_MAX 256

/* ASCII ETX — generated by Ctrl+C */
#define TTY_CTRL_C 0x03

/* ASCII SUB — generated by Ctrl+Z */
#define TTY_CTRL_Z 0x1A

/* Read ring buffer — completed lines are copied here */
static char read_buf[TTY_BUF_SIZE];
static volatile uint32_t read_head;  /* IRQ writes here */
static volatile uint32_t read_tail;  /* Process reads from here */

/* Count of complete lines available */
static volatile uint32_t lines_ready;

/* Line buffer — accumulates current line being typed */
static char line_buf[TTY_LINE_MAX];
static uint32_t line_pos;

/* PGID of the foreground process group (set on tty_read) */
static uint32_t tty_fg_pgid;

/* Wait queue for tty_read blocking */
static Spinlock tty_lock = SPINLOCK_INIT;
static WaitQueue tty_read_wq = WAITQUEUE_INIT;

/* Configurable output function — defaults to serial_putchar */
static void (*tty_output_fn)(char c);

/* Emit a character through the configured output */
static void tty_emit(char c) {
    if (tty_output_fn)
        tty_output_fn(c);
    else
        serial_putchar(c);
}

void tty_init(void) {
    read_head = 0;
    read_tail = 0;
    lines_ready = 0;
    line_pos = 0;
    tty_output_fn = NULL;
    kprintf("[TTY] Initialized\n");
}

void tty_set_output(void (*fn)(char c)) {
    tty_output_fn = fn;
}

void tty_input_char(char c) {
    /* Ctrl+C — send SIGINT to foreground process group */
    if (c == TTY_CTRL_C) {
        if (tty_fg_pgid != 0) {
            sig_send_group(tty_fg_pgid, SIGINT);
        }
        tty_emit('^');
        tty_emit('C');
        tty_emit('\n');
        return;
    }

    /* Ctrl+Z — send SIGTSTP to foreground process group */
    if (c == TTY_CTRL_Z) {
        if (tty_fg_pgid != 0) {
            sig_send_group(tty_fg_pgid, SIGTSTP);
        }
        tty_emit('^');
        tty_emit('Z');
        tty_emit('\n');
        return;
    }

    if (c == '\b' || c == 127) {
        /* Backspace: remove last char from line buffer */
        if (line_pos > 0) {
            line_pos--;
            /* Echo backspace sequence: move back, overwrite with space, move back */
            tty_emit('\b');
            tty_emit(' ');
            tty_emit('\b');
        }
        return;
    }

    if (c == '\n' || c == '\r') {
        /* Newline: copy line buffer + '\n' into read ring buffer */
        for (uint32_t i = 0; i < line_pos; i++) {
            read_buf[read_head & TTY_BUF_MASK] = line_buf[i];
            read_head++;
        }
        read_buf[read_head & TTY_BUF_MASK] = '\n';
        read_head++;
        line_pos = 0;
        lines_ready++;
        wq_wake(&tty_read_wq);

        /* Echo newline */
        tty_emit('\n');
        return;
    }

    /* Regular character: append to line buffer if room */
    if (line_pos < TTY_LINE_MAX - 1) {
        line_buf[line_pos++] = c;
        tty_emit(c);
    }
}

int tty_read(void *buf, uint32_t count) {
    if (count == 0) return 0;

    /* Track foreground process group for Ctrl+C / Ctrl+Z */
    Process *cur = proc_current();
    if (cur != NULL) {
        tty_fg_pgid = cur->pgid;
    }

    /* Sleep until a complete line is available */
    spinlock_acquire(&tty_lock);
    while (lines_ready == 0) {
        wq_sleep(&tty_read_wq, &tty_lock);
        spinlock_acquire(&tty_lock);
    }
    spinlock_release(&tty_lock);

    /* Copy from ring buffer up to count bytes, stop after '\n' */
    char *out = (char *)buf;
    uint32_t copied = 0;
    while (copied < count && read_tail != read_head) {
        char ch = read_buf[read_tail & TTY_BUF_MASK];
        read_tail++;
        out[copied++] = ch;
        if (ch == '\n') break;
    }

    /* If we consumed a full line (ended with '\n'), decrement counter */
    if (copied > 0 && out[copied - 1] == '\n') {
        lines_ready--;
    }

    return (int)copied;
}

void tty_set_fg_pid(uint32_t pid) {
    tty_fg_pgid = pid;  /* Backward compat: treats pid as pgid */
}

void tty_set_fg_pgid(uint32_t pgid) {
    tty_fg_pgid = pgid;
}

int tty_write(const void *buf, uint32_t count) {
    const char *src = (const char *)buf;
    for (uint32_t i = 0; i < count; i++) {
        tty_emit(src[i]);
    }
    return (int)count;
}
